// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kzfrnenyoquubjyojbvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZnJuZW55b3F1dWJqeW9qYnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjk1ODIsImV4cCI6MjA2NTUwNTU4Mn0.nNzHd_b6dYjD8uTZ8cBhO9LSQcce6U0PaLAyPp1pziU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);